version: "3.8"
services:
  dev-odoo-santosa:
    restart: unless-stopped
    ports:
      - "8075:8069"
    depends_on:
      - dev-postgres-santosa
    env_file: santosa-project/env/dev.env

  dev-postgres-santosa:
    image: postgres:15
    container_name: dev-postgres-santosa
    ports:
      - "5435:5432"
    restart: unless-stopped
    env_file: santosa-project/env/dev.env
    volumes:
      - ./santosa-project/pg-data:/var/lib/pgsql/data/pgdata
    networks:
      - dev-santosa_project_network
    shm_size: '1gb'  # Bisa bantu untuk improve query besar
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=4GB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_connections=200"