version: "3.8"
services:
  odoo-santosa:
    restart: unless-stopped
    ports:
      - "8234:8069"
    depends_on:
      - postgres-santosa
    env_file: santosa-project/env/dev.env

  postgres-santosa:
    image: postgres:15
    container_name: postgres-santosa
    ports:
      - "5434:5432"
    restart: unless-stopped
    env_file: santosa-project/env/dev.env
    volumes:
      - ./santosa-project/pg-data:/var/lib/pgsql/data/pgdata
    networks:
      - santosa_project_network