from . import res_territory
from . import hr_employee
from . import hr_department
from . import division
from . import hr_employee_address
from . import employee_level
from . import hr_employee_family
from . import hr_employee_relation
from . import hr_employee_assets
from . import employee_educations
from . import hr_employee_certification
from . import hr_employment_log
from . import hr_payroll_entry
from . import hr_mutations
from . import res_branch
from . import directorate
from . import hr_contract
from . import hr_tms_open_close
from . import hr_warning_letter
from . import hr_warning_letter_type
from . import hr_pasal_pelanggaran
from . import hr_employee_document
from . import hr_document
from . import document_type
from . import department
from . import hr_emp_status
from . import hr_resignation
from . import employment_tracking
from . import hr_checking_id